<!-- Lumos! :) -->
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <?php /* echo $this->getChildHtml('head') */ ?>
</head>

<body>
<div id="wrapper" class="border">

    <?php /* echo $this->getChildHtml('header') */ ?>

    <div id="content" class="product">
        <?php /* echo $this->getChildHtml('content') */ ?>
    </div>

    <?php /* echo $this->getChildHtml('footer') */ ?>

</div>
</body>
</html>