<div id="footer" class="border">
    <?php echo $this->__('Help Us to Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking"
                                                                    onclick="this.target='_blank'"><strong><?php echo $this->__('Report All Bugs') ?></strong></a>
    <?php echo $this->__('(ver. %s)', Mage::getVersion()) ?> <?php echo $this->getCopyright() ?></address>
</div>